import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";

export default function Home() {
  const [data, setData] = useState({ a: null, b: null, calc_type: null });
  const [result, setResult] = useState(null);
  const handleInputChange = (e) => {
    const {
      target: { name, value },
    } = e;
    setData((prevState) => ({ ...prevState, [name]: value }));
    console.log(data);
  };
  console.log(data);
  const xyz = async (e) => {
    e.preventDefault();
    const bodyFile = {
      method: "POST",
      headers: { "Content-Type": "aplication/json" },
      body: JSON.stringify(data),
    };
    const response = await fetch("/api/hello", bodyFile).then((t) => t.json());
    setResult(response.result);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form onSubmit={xyz}>
          <input type="number" name="a" required onChange={handleInputChange} />
          <input type="number" name="b" required onChange={handleInputChange} />
          <input
            type="radio"
            id="sum"
            name="calc_type"
            onChange={handleInputChange}
            value="sum"
          />
          <label htmlFor="sum">Sum</label>

          <input
            type="radio"
            id="mult"
            name="calc_type"
            onChange={handleInputChange}
            value="mult"
          />
          <label htmlFor="mult">Mult</label>
          <button type="submit">Submit</button>
        </form>
        {result}
      </main>
    </div>
  );
}
